root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
entrypoint = "./tmp/server"
include_ext = ["go"]
exclude_dir = ["web", "tmp", "vendor", ".git"]
exclude_regex = ["_test.go"]
delay = 1000
kill_delay = "1s"
log = "build-errors.log"
send_interrupt = false

[log]
time = false

[misc]
clean_on_exit = true
